---
- name: Install utility packages.
  become: yes
  apt:
    name:
    - python3-pip

- name: Install Docker Python SDK
  become: yes
  pip:
    name:
      - docker
    state: present

- name: Start and enable Docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull GPU environment
  become: yes
  docker_image:
    name: "{{ docker_registry }}{{ gpu_environment_name }}{{ extra_suffix }}"
    source: pull

- name: Retag GPU environment
  become: yes
  docker_image:
    name: "{{ docker_registry }}{{ gpu_environment_name }}{{ extra_suffix }}"
    repository: "{{ gpu_environment_name }}"
    force_tag: yes
    source: local

- name: Pull CPU environment
  become: yes
  docker_image:
    name: "{{ docker_registry }}{{ cpu_environment_name }}{{ extra_suffix }}"
    source: pull

- name: Retag CPU environment
  become: yes
  docker_image:
    name: "{{ docker_registry }}{{ cpu_environment_name }}{{ extra_suffix }}"
    repository: "{{ cpu_environment_name }}"
    force_tag: yes
    source: local
